app/src/MyPet/CMS/Controller/Ajax.php
<?php
namespace MyPet\CMS\Controller;

use KMCore\CMS\Classes\PageVariable;
use KMCore\CMS\Controller\JsonController;
use KMCore\Config\Config;
use MyPet\Users\Classes\AuthManager;
use MyPet\Users\Classes\UserManager;
use MyPet\Users\Model\User;

/**
 * Контроллер по умолчанию
 */
class Ajax extends JsonController
{
	const EVENT_CONTROLLER_AFTER_USERID = 'event.controller.after.userId';

	/**
	 * Инициализация гостя
	 */
	public function __construct()
	{
		parent::__construct();
		if (!(bool)$this->server->getContainer('config')->get('enable', 'cms'))
		{
			exit('Site is disable');
		}
		UserManager::initUserId();
	}

	/**
	 * @param array  $data
	 * @param string $renderFile
	 * @return string
	 */
	protected function response(Array $data = [], $renderFile = '')
	{
		$data['loggedIn'] = AuthManager::loggedIn();
		$data['userId'] = AuthManager::getSessionUserId();
		$data['email'] = AuthManager::getSessionEmail();

		$data['messages'] = $this->server->getContainer('helperFactory')->getRedirectHelper()->showMessage();
		$data['errors'] = $this->server->getContainer('helperFactory')->getRedirectHelper()->showErrors();

		$user = new User(['id' => (string)$data['userId']]);
		if ($user->isLoadedObject())
		{
			$data['user']['first_name'] = $user->first_name;
			$data['user']['last_name'] = $user->last_name;
			$data['user']['photo'] = $user->photo;
			$data['user']['id'] = $user->id;
			$data['user']['profession'] = $user->profession;
		}

		$userPageId = $this->request->getRequest('userId', '');
		if (empty($userPageId))
		{
			$userPageId = $this->request->getRequest('type', '');
		}
		$data['isYou'] = (empty($userPageId) || $data['userId'] === $userPageId);

		if (!empty($userPageId))
		{
			$user = new User(['id' => (string)$userPageId]);
			if ($user->isLoadedObject())
			{
				$data['userPageId'] = $userPageId;
				$data['author']['first_name'] = $user->first_name;
				$data['author']['last_name'] = $user->last_name;
				$data['author']['photo'] = $user->photo;
				$data['author']['id'] = $user->id;
				$data['author']['profession'] = $user->profession;
			}
		}

		foreach ($data['messages'] as &$item)
		{
			$item = $this->server->getContainer('config')->loadFile('translate')->get(
				PageVariable::getLangName(),
				$item,
				Config::TYPE_MAIN,
				$item
			);
		}
		foreach ($data['errors'] as &$item)
		{
			$item = $this->server->getContainer('config')->loadFile('translate')->get(
				PageVariable::getLangName(),
				$item,
				Config::TYPE_MAIN,
				$item
			);
		}

		parent::response($data, $renderFile);
	}
}

app/src/MyPet/CMS/Controller/Index.php
<?php
namespace MyPet\CMS\Controller;

use KMCore\CMS\Classes\PageVariable;
use KMCore\CMS\Controller\PageController;
use KMCore\Config\Config;
use MyPet\Friends\Classes\FriendsManager;
use MyPet\Pets\Classes\PetManager;
use MyPet\Users\Classes\AuthManager;
use MyPet\Users\Classes\UserManager;
use MyPet\Users\Model\User;
use Pimple\Container;

/**
 * Контроллер по умолчанию
 */
class Index extends PageController
{
	const EVENT_CONTROLLER_AFTER_USERID = 'event.controller.after.userId';

	/**
	 * Инициализация гостя
	 */
	public function __construct()
	{
		parent::__construct();
		if (!(bool)$this->server->getContainer('config')->get('enable', 'cms'))
		{
			exit('Site is disable');
		}

		$this->server->on(
			self::EVENT_CONTROLLER_AFTER_USERID,
			function (PageController $controller)
			{
				$container = $controller->server->getContainer();
				$container['petManager'] = function (Container $c)
				{
					return new PetManager($GLOBALS['serverContainer']);
				};
				$container['friendsManager'] = function (Container $c)
				{
					return new FriendsManager();
				};
			}
		);

		UserManager::initUserId();
		$this->server->emit(self::EVENT_CONTROLLER_AFTER_USERID, [$this]);
	}

	/**
	 * @param array  $data
	 * @param string $renderFile
	 * @return string
	 */
	protected function response(Array $data = [], $renderFile = '')
	{
		$data['loggedIn'] = AuthManager::loggedIn();
		$data['userId'] = AuthManager::getSessionUserId();
		$data['email'] = AuthManager::getSessionEmail();

		$data['messages'] = $this->server->getContainer('helperFactory')->getRedirectHelper()->showMessage();
		$data['errors'] = $this->server->getContainer('helperFactory')->getRedirectHelper()->showErrors();

		$user = new User(['id' => (string)$data['userId']]);
		if ($user->isLoadedObject())
		{
			$data['user']['first_name'] = $user->first_name;
			$data['user']['last_name'] = $user->last_name;
			$data['user']['photo'] = $user->photo;
			$data['user']['id'] = $user->id;
			$data['user']['profession'] = $user->profession;
		}

		$userPageId = $this->request->getRequest('userId', '');
		if (empty($userPageId))
		{
			$userPageId = $this->request->getRequest('type', '');
		}
		$data['isYou'] = (empty($userPageId) || $data['userId'] === $userPageId);

		if (!empty($userPageId))
		{
			$user = new User(['id' => (string)$userPageId]);
			if ($user->isLoadedObject())
			{
				$data['userPageId'] = $userPageId;
				$data['author']['first_name'] = $user->first_name;
				$data['author']['last_name'] = $user->last_name;
				$data['author']['photo'] = $user->photo;
				$data['author']['id'] = $user->id;
				$data['author']['profession'] = $user->profession;
			}
		}

		foreach ($data['messages'] as &$item)
		{
			$item = $this->server->getContainer('config')->loadFile('translate')->get(
				PageVariable::getLangName(),
				$item,
				Config::TYPE_MAIN,
				$item
			);
		}
		foreach ($data['errors'] as &$item)
		{
			$item = $this->server->getContainer('config')->loadFile('translate')->get(
				PageVariable::getLangName(),
				$item,
				Config::TYPE_MAIN,
				$item
			);
		}

		parent::response($data, $renderFile);
	}
}

app/src/MyPet/CMS/Controller/SearchHelper.php
<?php
namespace MyPet\CMS\Controller;

use KMCore\BaseController;
use KMCore\DB\Elasticsearch\Common\Exceptions\UnexpectedValueException;
use KMCore\DB\Elasticsearch\ElasticsearchManager;
use KMCore\Helper\ArrayDataHelper;
use MyPet\CMS\Classes\Plugins\Page\AboutPet;
use MyPet\Location\Model\City;
use MyPet\Pets\Model\BreedModel;
use MyPet\Users\Classes\AuthManager;

/**
 * @author Maxim Tkach <gollariel@gmail.com>
 */
class SearchHelper extends BaseController
{
	public function findMixed()
	{
		if (!AuthManager::loggedIn())
		{
			throw new UnexpectedValueException('Not auth user');
		}

		$userId = AuthManager::getSessionUserId();

		$langName = $this->server->getContainer('sessionStorage')->get('langName');

		$perPage = 10;
		$from = (int)$this->request->getGetOrPost('from', 0);
		$query = $this->request->getGetOrPost('query', '', true);
		$params = [];
		$params['index'] = 'mypet';
		$params['size'] = $perPage;
		$params['from'] = $from;
		$query_string['query'] = $query;
		$query_string['fields'] = ["nick", "hNick", "email", "*_name"];
		$params['body']['query']['query_string'] = $query_string;

		$data = ElasticsearchManager::getInstance()->search($params);

		$breeds = [];
		if (isset($data['hits']['hits']))
		{
			foreach ($data['hits']['hits'] as &$item)
			{
				if ($item['_type'] === 'pet')
				{
					$item['_source']['age'] = AboutPet::getAgeToRender($item['_source'], $langName);
					if (isset($item['_source']['breed']) && !empty($item['_source']['breed']))
					{
						try
						{
							$breeds[] = new \MongoId($item['_source']['breed']);
						}
						catch (\Exception $e)
						{

						}
					}

				}
			}

			$breeds = BreedModel::getAllAdvanced(['_id' => ['$in' => $breeds]]);
			$breeds = ArrayDataHelper::arrayByOneKey($breeds, '_id');

			foreach ($data['hits']['hits'] as $k => &$item)
			{
				if ($item['_type'] === 'user')
				{
					$item['sort'] = $k;
				}
				elseif ($item['_type'] === 'pet')
				{
					$item['_source']['render_breed'] = '';
					if (isset($item['_source']['breed']))
					{
						$breed = $item['_source']['breed'];
						if (isset($breeds[$breed][$langName]))
						{
							$item['_source']['render_breed'] = $breeds[$breed][$langName];
						}
						elseif (isset($breeds[$breed]))
						{
							$item['_source']['render_breed'] = $breeds[$breed]['en'];
						}
					}

					$isYourPet = (array_search($userId, $item['_source']['ownerIds']) !== false);
					$item['sort'] = $k;
					if ($isYourPet)
					{
						$item['sort'] += 1000;
					}
				}
			}
			ArrayDataHelper::keyMultiSort($data['hits']['hits'], 'sort', true, false, false);
		}
		$this->response->json($data);
	}
} 

app/src/MyPet/CP/Controller/AdminUser.php
<?php
namespace MyPet\CP\Controller;

use KMCore\Admin\Classes\Main;
use KMCore\Admin\Controller\AdminController;
use KMCore\Helper\RedirectManager;

/**
 * Страница администраторов
 *
 * @author Vasiliy Khvostik
 */
class AdminUser extends AdminController
{
	/**
	 * Страница генерации паролей администраторами
	 *
	 * @return string
	 */
	public function generator()
	{
		$data = (string)$this->request->getGetOrPost('data', '');
		$hash = (string)$this->request->getGetOrPost('hash', '');
		$action = (string)$this->request->getGetOrPost('action', '');

		if (!empty($data) && !empty($hash))
		{
			if ($hash == "password")
			{
				$result = md5($data.$this->server->getContainer('config')->get("authSalt"));
			}
			else
			{
				$result = hash($hash, $data);
			}

			RedirectManager::showMessage('Успешно сгенерирован!');
		}
		else
		{
			if ($action == 'generate')
			{
				RedirectManager::showErrors('Исходные данные не должны быть пустыми!');
			}
			$result = "";
		}

		return $this->render('generator.html.twig', ['data' => $data, 'hash' => $hash, 'result' => $result]);
	}

	public function createIndex()
	{
		if (isset($_SESSION['auth']['isRoot']))
		{
			$value = $this->server->getContainer('config')->loadFile('adminMenu')->get('menu');
			$this->processingMenu($value);
		}
		RedirectManager::redirect('/CP/KMCore_Admin_Model_AdminUser');
	}

	/**
	 * @param $value
	 */
	private function processingMenu($value)
	{
		if (is_array($value))
		{
			foreach ($value as $v)
			{
				if (is_array($v))
				{
					$this->processingMenu($v);
				}
				else
				{
					$modelClassName = '\\'.str_replace('_', '\\', $v);
					if (class_exists($modelClassName))
					{
						Main::getEntityIndexes($modelClassName, true, true);
					}
				}
			}
		}
		else
		{
			$modelClassName = '\\'.str_replace('_', '\\', $value);
			if (class_exists($modelClassName))
			{
				Main::getEntityIndexes($modelClassName, true, true);
			}
		}
	}
}

app/src/MyPet/CP/Controller/Index.php
<?php
namespace MyPet\CP\Controller;

use KMCore\Admin\Controller\BaseAdminController;

/**
 * Основной контроллер работы с админкой
 *
 * @author Vasiliy Khvostik <vasyakhvostik@gmail.com>
 */
class Index extends BaseAdminController
{

}

app/src/MyPet/CP/Controller/Pages.php
<?php
namespace MyPet\CP\Controller;

use KMCore\Admin\Controller\AdminController;
use KMCore\Helper\RedirectManager;

/**
 * Страница администраторов
 */
class Pages extends AdminController
{
	/**
	 * Страница генерации паролей администраторами
	 *
	 * @return string
	 */
	public function generator()
	{
		$data = (string)$this->request->getGetOrPost('data', '');
		$result = '';
		if (!empty($data))
		{
			$result = json_encode($data);
			RedirectManager::showMessage('Успешно сгенерирован!');
		}

		return $this->render('prepare.html.twig', ['data' => $data, 'result' => $result]);
	}
}

app/src/MyPet/FacebookCanvas/Controller/FacebookCanvas.php
<?php
namespace MyPet\FacebookCanvas\Controller;
use KMCore\BaseController;

/**
 * Class FacebookCanvas
 * @author Maxim Tkach <gollariel@gmail.com>
 */
class FacebookCanvas extends BaseController
{
	public function app()
	{
		$content = 'Hello world!';

		$view = realpath(__DIR__.'/..');
		$output = $this->server->getContainer('render')->render($view.'/Views/facebook_canvas.html.twig', ['content' => $content]);
		$this->response->html($output);
	}
}

app/src/MyPet/FileUpload/Controller/Mechanic/CroppicUpload.php
<?php
namespace MyPet\FileUpload\Controller\Mechanic;

/**
 * @author Maxim Tkach <gollariel@gmail.com>
 */
abstract class CroppicUpload extends ImageUpload
{
	public function upload()
	{
		$response = parent::upload();
		print json_encode($response);
	}

	public function crop()
	{

		$response = parent::crop();
		print json_encode($response);
	}
}

app/src/MyPet/FileUpload/Controller/Mechanic/FileUpload.php
<?php
namespace MyPet\FileUpload\Controller\Mechanic;

use KMCore\BaseController;
use KMCore\DB\Elasticsearch\Common\Exceptions\UnexpectedValueException;
use MyPet\Users\Classes\AuthManager;

/**
 * @author Maxim Tkach <gollariel@gmail.com>
 */
class FileUpload extends BaseController
{
	protected $pathToImage;
	protected $pathToUserUploadDir;
	protected $urlToUserUploadDir;
	protected $allowedExts;
	protected $imagine;

	/**
	 *
	 */
	public function __construct()
	{
		parent::__construct();

		if (!AuthManager::loggedIn())
		{
			throw new UnexpectedValueException('Not auth user');
		}
		$userId = AuthManager::getSessionUserId();

		$this->pathToImage = PUBLIC_PATH.'/files';
		$this->pathToUserUploadDir = $this->pathToImage.'/'.$userId;
		$this->urlToUserUploadDir = $this->server->getContainer('config')->get('cdnUrl').'/files/'.$userId;
		if (!file_exists($this->pathToUserUploadDir))
		{
			mkdir($this->pathToUserUploadDir);
		}
	}

	protected function getType()
	{
		return 'file';
	}

	protected function getName($extension, $prefix = '')
	{
		return $prefix.rand(0, 1000).time(true).rand(0, 1000).'.'.$extension;
	}
}

app/src/MyPet/Friends/Controller/FriendsController.php
<?php
namespace MyPet\Friends\Controller;

use MyPet\Friends\Classes\FriendsManager;
use MyPet\Friends\Classes\InteractionOfFriends;
use MyPet\Friends\Model\FriendsModel;
use MyPet\Inbox\Classes\RequestData;
use MyPet\Inbox\Classes\RequestManager;
use MyPet\ApiController;

/**
 * Контроллер управления друзьями
 *
 * @api
 */
class FriendsController extends ApiController
{
	/**
	 * @var FriendsManager
	 */
	protected $friendsManager;

	/**
	 *
	 */
	public function __construct()
	{
		parent::__construct();
		$this->friendsManager = new FriendsManager();
	}

	public function add()
	{
		$id = (string)$this->user->id;
		$friendId = (string)$this->request->getGetOrPost('friendId', '');

		$userObj = $this->user;
		$this->friendsManager->on(
			FriendsManager::EVENT_FRIEND_ADD,
			function (FriendsModel $user) use ($userObj)
			{
				$attributes = [
					'userId'   => $user->id,
					'friendId' => $user->friendId,
					'payload'  => $userObj->getFieldsSanitized(),
				];
				RequestData::init(new RequestData($user->friendId))->setType(
					RequestManager::TYPE_INVITE_CONFIRM
				)->setAttributes($attributes)->setUnique($user->_id)->setPub(true)->update();
			}
		);

		$this->friendsManager->on(
			FriendsManager::EVENT_FRIEND_CONFIRM,
			function (FriendsModel $user) use ($userObj)
			{
				$manger = new RequestManager();
				$manger->collectRequest((string)$user->_id, $this->user->id);
			}
		);

		if (!empty($friendId))
		{
			$this->friendsManager->addFriend($id, $friendId);
		}

		$this->data = ['success' => true];
		$this->success = true;
		$this->response();
	}

	public function delete()
	{
		$id = (string)$this->user->id;
		$friendId = (string)$this->request->getGetOrPost('friendId', '');

		$this->friendsManager->remFriend($id, $friendId);

		$this->data = ['success' => true];
		$this->success = true;
		$this->response();
	}

	public function count()
	{
		$id = (string)$this->user->id;
		$count = $this->friendsManager->countFriends($id);

		$this->data['count'] = $count;
		$this->success = true;
		$this->response();
	}

	public function getFriends()
	{
		$id = (string)$this->user->id;
		$page = (int)$this->request->getGetOrPost('page', 0);
		$results = $this->friendsManager->getFriends($id, $page, FriendsManager::FRIENDS_PER_PAGE);
		$pages = $this->friendsManager->countPagesFriend($id, FriendsManager::FRIENDS_PER_PAGE);
		$count = $this->friendsManager->countFriends($id);

		$this->data['friends'] = $results;
		$this->data['pages'] = $pages;
		$this->data['perPage'] = FriendsManager::FRIENDS_PER_PAGE;
		$this->data['count'] = $count;
		$this->success = true;
		$this->response();
	}

	public function getFriendProfiles()
	{
		$id = (string)$this->user->id;
		$page = (int)$this->request->getGetOrPost('page', 0);
		$results = $this->friendsManager->getFriends($id, $page, FriendsManager::PROFILES_PER_PAGE);
		$pages = $this->friendsManager->countPagesFriend($id, FriendsManager::PROFILES_PER_PAGE);
		$count = $this->friendsManager->countFriends($id);

		$this->data['profiles'] = InteractionOfFriends::getProfileFriends($id, $results);
		$this->data['pages'] = $pages;
		$this->data['perPage'] = FriendsManager::PROFILES_PER_PAGE;
		$this->data['count'] = $count;
		$this->success = true;
		$this->response();
	}

	public function getUserProfile()
	{
		$id = (string)$this->user->id;
		$userIds = (array)$this->request->getGetOrPost('userIds', []);
		$userIds = array_slice($userIds, 0, 100);
		$ids = [];
		foreach ($userIds as $id)
		{
			if (!empty($id))
			{
				$ids[] = ['friendId' => $id];
			}
		}

		$this->data['profiles'] = InteractionOfFriends::getProfileFriends($id, $ids);
		$this->success = true;
		$this->response();
	}

	public function getProfile()
	{
		$id = (string)$this->user->id;
		$userId = (string)$this->request->getGetOrPost('friendId', '');

		$this->data['profiles'][] = InteractionOfFriends::getProfile($id, [$userId]);
		$this->success = true;
		$this->response();
	}

	public function isFriend()
	{
		$id = (string)$this->user->id;
		$friendId = (string)$this->request->getGetOrPost('friendId', '');

		$this->data['isFriend'] = $this->friendsManager->isFriend($id, $friendId);

		$this->success = true;
		$this->response();
	}
}

app/templates/mypet/components/module_friends.html.twig
<div class="row module white">
	<div class="row header-top">
		{% if petId %}
			<a href="/specialists/{{ petId }}">
				<block_trn class="toTranslate">_t_specialists_t_</block_trn> <span>({{ count }})</span>
			</a>
		{% else %}
			<a href="/friends/{{ userId }}">
				<block_trn class="toTranslate">_t_friends_and_specialist_t_</block_trn> <span>({{ count }})</span>
			</a>
		{% endif %}
	</div>
	<div class="row module-body">
		{% if petId %}
			{% for item in specialists %}
				{% if item.id %}
					<div class="item">
						<a href="/user/{{ item.id }}">
							<div class="item-img cover-avatar avatar-user">
								{% if item.photo %}<img class="cover-avatar" src="{{ item.photo }}" alt=""/>{% endif %}
								<i class="icons"></i>
							</div>
							<span>{{ item.first_name }} {{ item.last_name }}</span>
						</a>
					</div>
				{% endif %}
			{% endfor %}
		{% else %}
			{% for item in friends %}
				{% if item.profile.id %}
					<div class="item">
						<a href="/user/{{ item.profile.id }}">
							<div class="item-img cover-avatar avatar-user">
								{% if item.profile.photo %}<img class="cover-avatar" src="{{ item.profile.photo }}" alt=""/>{% endif %}
								{% if item.profile.isProf == "yes" %}<i class="icons"></i>{% endif %}
							</div>
							<span>{{ item.profile.first_name }} {{ item.profile.last_name }}</span>
						</a>
					</div>
				{% endif %}
			{% endfor %}
		{% endif %}

	</div>
</div><!-- .module -->

app/templates/mypet/components/page_about_user.html.twig
	<div class="row page-content">
		{% if profile.isYou %}<a href="/user/me/edit" title="{{ pagecontent.edit.tooltip }}" class="edit tooltip">{{ pagecontent.edit.html|raw }}</a>{% endif %}
		{#<a href="#mp_page_about_me_edit" class="edit">Редагувати інформацію</a>#}
		<div class="section">
			<h2>{{ pagecontent.section.h2.html|raw }}</h2>
			<div class="section-body">
				<table>
					{% if profile.age %}
					<tr>
						<td>{{ pagecontent.section.body.age|raw }}:</td>
						<td>{{ profile.age }}</td>
					</tr>
					{% endif %}
					{% if profile.user_country_render %}
					<tr>
						<td>{{ pagecontent.section.body.user_country|raw }}:</td>
						<td>{{ profile.user_country_render }}</td>
					</tr>
					{% endif %}
					{% if profile.region_render %}
					<tr>
						<td>{{ pagecontent.section.body.region|raw }}:</td>
						<td>{{ profile.region_render }}</td>
					</tr>
					{% endif %}
					{% if profile.city_render %}
						<tr>
							<td>{{ pagecontent.section.body.city|raw }}:</td>
							<td>{{ profile.city_render }}</td>
						</tr>
					{% endif %}
					{% if profile.phone %}
						<tr>
							<td>{{ pagecontent.section.body.phone|raw }}:</td>
							<td>
								<ul>
									{% for item in profile.phone %}
										<li>{{ item }}</li>
									{% endfor %}
								</ul>
							</td>
						</tr>
					{% endif %}
					{% if profile.socLinks %}
					<tr>
						<td>{{ pagecontent.section.body.socLinks|raw }}:</td>
						<td>
							<ul>
								{% for item in profile.socLinks %}
									<li><a href="{{ item }}">{{ item }}</a></li>
								{% endfor %}
							</ul>
						</td>
					</tr>
					{% endif %}
					{% if profile.about %}
					<tr>
						<td>{{ pagecontent.section.body.about|raw }}:</td>
						<td>{{ profile.about }}</td>
					</tr>
					{% endif %}
					{% if profile.isProf === 'yes' and profile.profession %}
						<tr>
							<td>{{ pagecontent.section.body.profession|raw }}:</td>
							<td>{{ profile.profession_render }}</td>
						</tr>
					{% endif %}
					{% if profile.isProf === 'yes' and profile.skills %}
						<tr>
							<td>{{ pagecontent.section.body.skills|raw }}:</td>
							<td>
								<ul>
									{% for item in profile.skills %}
										<li>{{ item }}</li>
									{% endfor %}
								</ul>
							</td>
						</tr>
					{% endif %}
				</table>
			</div>
		</div><!-- .section -->
			{% for item in works %}
				<div class="section">
					<h2 class="toTranslate">_t_{{ item.type }}_t_</h2>
					{% for result in item.work %}
						<div class="section-body">
							<table>
								<tr>
									<td class="toTranslate">_t_name_t_:</td>
									<td>{{ result.name }}</td>
								</tr>
								{% if result.start_y or result.end_y %}
								<tr>
									<td class="toTranslate">_t_period_t_:</td>
									<td>{{ result.start_y }} - {{ result.end_y }}</td>
								</tr>
								{% endif %}
								{% for elm in result.params %}
								{% if elm.type and elm.value %}
									<tr>
										<td class="toTranslate">_t_{{ elm.type }}_t_:</td>
										<td>{{ elm.value }}</td>
									</tr>
								{% endif %}
								{% endfor %}
							</table>
						</div>
					{% endfor %}
				</div><!-- .section -->
			{% endfor %}
	</div><!-- .page-content-->

app/templates/mypet/components/page_friends.html.twig
<div class="row page-content">
	{% if loggedIn %}
		<a class="page-content-link" href="/search">{{ pagecontent.content_link.html|raw }}</a>
	{% endif %}

	<div class="section">
		<h2>{{ pagecontent.section.h2.html|raw }} <span>({{ count }})</span></h2>
		<div class="container_post section-body list-content">

			{% for item in friends %}
				<div class="item_post section list-content__item {% if (loop.index0 % 2) != 0  %}gray{% endif %}">
					<div class="list-content__photo">
						<a href="/user/{{ item.userId }}">
							<div class="cover-avatar avatar-user">
							<img class="cover-avatar" src="{% if item.profile.photo %}{{ item.profile.photo }}{% endif %}" alt=""/>
							{% if item.profile.isProf == "yes" %}<i class="icons"></i>{% endif %}
							</div>
						</a>
					</div>
					<div class="list-content__body">
						<h3><a href="/user/{{ item.userId }}">{{ item.profile.first_name }} {{ item.profile.last_name }}</a></h3>
						<div class="description">{% if item.profile.status %}{{ item.profile.status }},{% endif %} {{ item.profile.age }}</div>
						<div class="row">
							<ul class="list-content__pets ">
								{% for petId,pet in item.profile.pets_photo %}
									<li class="search-avatar avatar-{{ pet.type }}"><a href="/pet/{{ petId }}">{% if pet.photo %}<img src="{{ pet.photo }}" alt=""/>{% endif %}</a></li>
								{% endfor %}
							</ul>
						</div>

					</div>
					<div class="list-content__link">
						<ul>
							{% if isYou %}
							<li><a onclick='kmcore.api.message.create("{{ item.userId }}", function(data){
                                        if(data.success && data.response._id)
                                        {
                                            openPopup("mp_popup_new_message", "friendId={{ item.userId }}&dialogId="+data.response._id);
                                            return false;
                                        }
                                        });' href="#">{{ pagecontent.section.body.create|raw }}</a></li>
							<li><a href="#" onclick='kmcore.api.friend.deleteFriend("{{ item.userId }}")'>{{ pagecontent.section.body.deleteFriend|raw }}</a></li>
							{% endif %}
							{#<li><a href="/user/{{ item.userId }}">{{ pagecontent.section.body.view|raw }}</a></li>#}
						</ul>
					</div>
				</div><!--.list-content__item -->
			{% endfor %}
		</div><!-- .friends-list -->
		<div id="pagination_post">
			{% set last_page = pages %}
			{% for i in 0..last_page %}
				<a href="/friends/{{ userId }}/{{ i }}" {% if page+1 == i %}class="next_post"{% endif %}>{{ i }}</a>
			{% endfor %}
		</div>
		<script>
			var ias = $.ias({
				container:  ".container_post",
				item:       ".item_post",
				pagination: "#pagination_post",
				next:       ".next_post"
			});

			ias.extension(new IASSpinnerExtension());            // shows a spinner (a.k.a. loader)
			ias.extension(new IASTriggerExtension({offset: 3})); // shows a trigger after page 3
			ias.extension(new IASNoneLeftExtension({
				text: 'There are no more pages left to load.'      // override text when no pages left
			}));
		</script>
	</div><!-- .section -->
</div><!-- .page-content-->